Protect against failures when killing a running topology.
If any of the state in zookeeper is deleted while others are left in
tact the topology will become undeployable because the cli will fail to
clean up the leftover state. The exception looks like:

```
[2016-07-21 13:42:23 +0000] com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor SEVERE:  Exception processing future
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to fetch data from path: /heron/executionstate/foo
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
        at com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor.awaitResult(SchedulerStateManagerAdaptor.java:71)
        at com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor.awaitResult(SchedulerStateManagerAdaptor.java:63)
        at com.twitter.heron.spi.statemgr.SchedulerStateManagerAdaptor.getExecutionState(SchedulerStateManagerAdaptor.java:198)
        at com.twitter.heron.scheduler.RuntimeManagerMain.validateRuntimeManage(RuntimeManagerMain.java:351)
        at com.twitter.heron.scheduler.RuntimeManagerMain.manageTopology(RuntimeManagerMain.java:306)
        at com.twitter.heron.scheduler.RuntimeManagerMain.main(RuntimeManagerMain.java:251)
```

This change makes it so the kill command is more robust and will treat
instances where the state does not exist as a no-op and continue its
clean up.